# For local development, only database is running
#
# docker compose up -d
# uvicorn app.main:app --reload
#

services:
  postgres_db:
    restart: unless-stopped
    image: postgres:16
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_SETTINGS__DB}
      - POSTGRES_USER=${DB_SETTINGS__USERNAME}
      - POSTGRES_PASSWORD=${DB_SETTINGS__PASSWORD}
    env_file:
      - .env.example
    ports:
      - "${DB_SETTINGS__PORT}:5432"

volumes:
  postgres_db:
