name: tests
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"
  pull_request:
    types: [opened, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: /opt/venv

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            /opt/venv
          key: venv-${{ runner.os }}-python-3.12.2-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies and activate virtualenv
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path /opt/venv
          poetry install --no-interaction --no-root
          echo "/opt/venv/$(ls /opt/venv)/bin" >> $GITHUB_PATH

      - name: Run tests
        env:
          SECURITY__JWT_SECRET_KEY: very-not-secret
          DATABASE__HOSTNAME: localhost
          DATABASE__PASSWORD: postgres
        run: |
          source /opt/venv/$(ls /opt/venv)/bin/activate
          pytest
